# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 01a7d190b0117178bd67351b7848c30d5397ba68549c9a84ef38af10a923727e31aaeb851b82f9a6b7fcc7d218850d832b1f4611f88454fe08785321d35addc0

test:
  secret_key_base: 027a486118c3555b73aa8592c69726e01a953ce41112e55ab351e91a52211d5e1377ee646aaef024456f3d2f247aa6df0a39d80b3414dcd3a751ab69de76eb8a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
